---
- sudo: yes
  hosts: all
  tasks:
    - name: ensure base packages are installed
      yum: pkg={{ item }} state=installed
      with_items:
        - "bind-utils"
        - "psmisc"
        - "perl-libwww-perl"
        - "lsof"
        - "net-tools"
        - "golang"

    - name: "ensure dummy-api user exists"
      user: name="dummy-api" shell="/bin/bash"

    - name: "ensure init script is in place"
      copy: src="../etc/dummy-api.init" dest="/etc/init.d/dummy-api" mode=555

    - name: directories
      file: path="{{ item }}" state=directory owner="dummy-api" group="dummy-api"
      with_items:
        - "/var/log/dummy-api"
        - "/srv/dummy-api"

    - name: "ensure dummy-api is in place"
      copy: src="../dummy-api.go" dest="/srv/dummy-api/dummy-api.go" mode=444

    - name: "ensure dummy-api service is running"
      service: name="dummy-api" state=running enabled=yes

